name = "DisorderedPointClusters"
uuid = "bbfbc409-1cef-4d52-a349-b3dde267ef6f"
authors = ["Matthias Himmelmann <65544132+matthiashimmelmann@users.noreply.github.com>"]
version = "0.1.0"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
